runtime: nodejs12
env: standard
service: flickr-daily
handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon.ico
resources:
  memory_gb: 0.5
basic_scaling:
  max_instances: 1
  idle_timeout: 10m